name: General example
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  before-part:
    runs-on: ubuntu-latest
    name: Before Run
    steps:
      - name: Before part
        run: |
          echo "Some actions"
          echo "Before running support tests"
  # This workflow contains a single job called "support-test"
  support-test:
    needs: before-part
    # Support workflow which will be run
    # the eyes_version value should be equal to the current version in the sdk repo, and should be available in npm
    uses: applitools/applitools_support_matrix/.github/workflows/pre_release_run.yml@main
    with:
      last_passed: false
      sdk_versions_json: '[{ "name": "js/eyes-cypress", "version": "exact@3.36.2"}, {"name": "js/eyes-testcafe", "version": "exact@3.0.0"}, {"name": "python/eyes-selenium", "version": "exact@5.20.2"}, {"name": "java/eyes-playwright-java5", "version": "exact@5.64.2"}]'
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  after-part:
    needs: support-test
    runs-on: ubuntu-latest
    name: After Run
    steps:
      - name: After part
        run: |
          echo "Some actions"
          echo "Doing some staff after passing tests"
