name: JS_Example
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "support-test"
  support-test:
    # Support workflow which will be run
    uses: applitools/applitools_support_matrix/.github/workflows/js_selenium.yml@develop
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
