name: Python Example
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  before-part:
    runs-on: ubuntu-20.04
    name: Before Run
    outputs:
      version: ${steps.bump.outputs.version}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: applitools/eyes.sdk.javascript1
          ref: 'python_package'
      - uses: actions/setup-python@v3
        with:
          python-version: "3.6"
      - name: Bump test version
        id: bump
        working-directory: python/eyes_selenium
        run: |
          pip install bump2version
          bumpversion build --list
          version=$(cat .bumpversion.cfg | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\(\.[a-zA-Z]\+\)\?')
          echo $version
          echo "version=package@$version" >> $GITHUB_OUTPUT
        env:
          GIT_AUTHOR_NAME: ${{github.actor}}
          GIT_COMMITTER_NAME: ${{github.actor}}
          EMAIL: github-actions@github.com          
      - name: Build packages
        working-directory: python
        run: make dist
      - uses: actions/upload-artifact@v3
        with:
          name: package
          if-no-files-found: error
          # the * wildcard in pyth*n is not to match anything, but to prevent
          # upload-artifact from flattening python directory, e.g. uploading
          # it's contents without python directory itself.
          path: "pyth*n/*/dist/"
  # This workflow contains a single job called "support-test"
  support-test:
    needs: before-part
    # Support workflow which will be run
    uses: applitools/applitools_support_matrix/.github/workflows/python.yml@python_package
    with:
      last_passed: false
      checkout_ref: 'python_package'
      eyes_version: ${{ format('package@{0}', needs.before-part.outputs.version) }}
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      SAUCE_USERNAME: "empty"
      SAUCE_ACCESS_KEY: "empty"
  after-part:
    needs: support-test
    runs-on: ubuntu-latest
    name: After Run
    steps:
      - name: After part
        run: |
          echo "Some actions"
          echo "Doing some staff after passing tests"
      
