name: Python Example
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  before-part:
    runs-on: ubuntu-latest
    name: Before Run
    steps:
      - name: Before part
        run: |
          echo "Some actions"
          echo "Before running support tests"
  # This workflow contains a single job called "support-test"
  support-test:
    needs: before-part
    # Support workflow which will be run
    uses: applitools/applitools_support_matrix/.github/workflows/python.yml@python_package
    with:
      last_passed: false
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      SAUCE_USERNAME: "empty"
      SAUCE_ACCESS_KEY: "empty"
  after-part:
    needs: support-test
    runs-on: ubuntu-latest
    name: After Run
    steps:
      - name: After part
        run: |
          echo "Some actions"
          echo "Doing some staff after passing tests"
      
